### PR TITLE
Binaries to use jll artifacts

### PR DESCRIPTION
**Pull request by aviks**
This allows support for all platforms, including windows and mac, as well as arm and power. It also makes intialisation much easier, and allow this package to work with PkgCompiler. 

This requires Julia 1.3 at a minimum now. 

I have also, in this PR, removed the Manifest from the repo. I think it is best practice not to check in Manifests for libraries.

### CODE REVIEW

**Comment by dfdx** [comment]
Great, thank you! Upgrading to Julia 1.3 was mandatory anyway since we need to move checking for updates to a separate threads - current single-threaded implementation is more a hack than a good implementation. 
Do you have any users of RDKafka in mind that need a new version to be tagged? I have a bunch of improvements for the project, but realistically I'll get to them in several months at best, so I'll be happy to make any intermediate versions as well.

**Comment by aviks** [comment]
Thanks! I think it would be good to get a version tagged in the interim.

**Comment by dfdx** [comment]
Here we go:
https://github.com/JuliaRegistries/General/pull/22311

**Comment by dfdx** [comment]
Ok, that PR cannot be automatically merged because BinaryBuilder doesn't have minimal version requirement in `[compat]`. I'll search for the lowest supported version and add this line.

**Comment by dfdx** [comment]
I've fixed the registration PR and added a more detailed example into the README, everything else should work automatically.

**Pull request merged**
